import type { WizardSegmentConfig, WizardSegmentKey } from './wizard-segment-config';

export const WIZARD_SEGMENTS_EN: Record<WizardSegmentKey, WizardSegmentConfig> = {

  namorade: {
    titleStepTitle: 'What do you want the surprise to be called? 💜',
    titleStepDescription: 'This is the name that shows at the top of the page. It can be "For the love of my life" or just their name.',
    titlePlaceholder: 'Ex: For the love of my life 💜',
    messageStepTitle: 'What do you want to tell them? 💌',
    messageStepDescription: 'Write everything your heart wants to say. This message will be front and center.',
    messagePlaceholder: 'Since the day I met you, every moment by your side is...',
    dateStepTitle: 'When did it all start? 💕',
    dateStepDescription: 'The date that marks the beginning of you two. We\'ll build a live counter showing every day together.',
    galleryStepDescription: 'The best photos of you two — the ones that tell your story.',
    timelineStepDescription: 'The most memorable moments of your relationship, in order.',
    musicStepDescription: 'Your song, or a voice note just for them.',
    puzzleStepDescription: 'They solve the puzzle first to unlock the surprise — emotional start!',
    memoryStepDescription: 'A memory match game with your photos. Super cute.',
    quizStepTitle: 'Couple\'s Quiz',
    quizStepDescription: 'Questions only they would know. How well do they know you?',
    successTitle: 'Your surprise is ready! 💜',
    successSubtitle: 'Now send it and wait for the reaction.',
    whatsappMessage: 'Babe, I made a special surprise for you 💝 open it when you can',
  },

  mae: {
    titleStepTitle: 'Tribute title',
    titleStepDescription: 'The name that appears at the top. Ex: For the best mom in the world.',
    titlePlaceholder: 'Ex: For my mom 🌸',
    messageStepTitle: 'Your message to her',
    messageStepDescription: 'Write everything you\'ve always wanted to say. It\'s okay to cry.',
    messagePlaceholder: 'Mom, I\'ll never be able to put into words what you mean to me...',
    dateStepTitle: 'A special date',
    dateStepDescription: 'Her birthday, Mother\'s Day, or any date that means something to you both.',
    galleryStepDescription: 'Photos with her — the old ones, the recent ones, the ones you love most.',
    timelineStepDescription: 'The most memorable moments you\'ve lived together.',
    musicStepDescription: 'A song that reminds you of her, or a heartfelt voice note.',
    puzzleStepDescription: 'She solves the puzzle to reveal a special photo of you two.',
    memoryStepDescription: 'A memory match game with your photos. She\'ll love it.',
    quizStepTitle: 'How well does she know you?',
    quizStepDescription: 'Fun questions — does she really know everything about you?',
    successTitle: 'Tribute ready! 🌸',
    successSubtitle: 'Send it to her now and grab a tissue.',
    whatsappMessage: 'Mom, I made a special surprise for you 💝 open it here',
  },

  espouse: {
    titleStepTitle: 'Page title',
    titleStepDescription: 'The name at the top. Ex: "To the person I chose for life".',
    titlePlaceholder: 'Ex: For the love of my life 💍',
    messageStepTitle: 'Your declaration',
    messageStepDescription: 'Write from the heart. Everything you\'ve lived together deserves to be said.',
    messagePlaceholder: 'Every day by your side reminds me why I chose you — and I\'d choose you again...',
    dateStepTitle: 'Your date',
    dateStepDescription: 'Your wedding day, or when it all began. The counter will show your time together.',
    galleryStepDescription: 'The most beautiful photos of you two — wedding, travels, daily moments.',
    timelineStepDescription: 'Your story told through moments — from the beginning until today.',
    musicStepDescription: 'The wedding song, or any song that\'s yours together.',
    puzzleStepDescription: 'They solve the puzzle to reveal a special photo of you two.',
    memoryStepDescription: 'A memory match game with your best photos.',
    quizStepTitle: 'Couple\'s Quiz',
    quizStepDescription: 'Questions only they would know — show how well you truly know each other.',
    successTitle: 'Your surprise is ready! 💍',
    successSubtitle: 'Send it and wait for the reaction.',
    whatsappMessage: 'Love, I made something special for you 💝 open it when you can',
  },

  amige: {
    titleStepTitle: 'Tribute title',
    titleStepDescription: 'The name at the top. Ex: "For my best friend".',
    titlePlaceholder: 'Ex: For my best friend 🤍',
    messageStepTitle: 'Your message to them',
    messageStepDescription: 'Write what this friendship means to you. Happy tears allowed.',
    messagePlaceholder: 'You\'re one of those people life puts in your path that you can\'t imagine living without...',
    dateStepTitle: 'Friendship date',
    dateStepDescription: 'When you two met, or a special date between you.',
    galleryStepDescription: 'Your best photos together — adventures, hangouts, special moments.',
    timelineStepDescription: 'Your friendship story told through meaningful moments.',
    musicStepDescription: 'A song that\'s yours together, or a heartfelt voice note.',
    puzzleStepDescription: 'They solve the puzzle to reveal a special photo.',
    memoryStepDescription: 'A memory match game with your photos. So much fun.',
    quizStepTitle: 'How well do they know you?',
    quizStepDescription: 'Questions only your best friend would know.',
    successTitle: 'Tribute ready! 🤍',
    successSubtitle: 'Send it and prepare for the reaction.',
    whatsappMessage: 'I made a special surprise for you 🤍 open it when you can',
  },

  pai: {
    titleStepTitle: 'Tribute title',
    titleStepDescription: 'The name at the top. Ex: For the best dad in the world.',
    titlePlaceholder: 'Ex: For my dad 💙',
    messageStepTitle: 'Your message to him',
    messageStepDescription: 'Everything you\'ve always wanted to tell your dad. Now is the time.',
    messagePlaceholder: 'Dad, it\'s not always easy to put into words what you mean to me...',
    dateStepTitle: 'A special date',
    dateStepDescription: 'Father\'s Day, his birthday, or any meaningful date between you.',
    galleryStepDescription: 'Photos with him — childhood, recent, the ones you treasure.',
    timelineStepDescription: 'The most memorable moments you\'ve lived together.',
    musicStepDescription: 'A song that reminds you of him, or a heartfelt voice note.',
    puzzleStepDescription: 'He solves the puzzle to reveal a special photo of you two.',
    memoryStepDescription: 'A memory match game with your photos. He\'ll love it.',
    quizStepTitle: 'How well does he know you?',
    quizStepDescription: 'Fun questions — does your dad know everything about you?',
    successTitle: 'Tribute ready! 💙',
    successSubtitle: 'Send it to him now.',
    whatsappMessage: 'Dad, I made a special surprise for you 💝 open it here',
  },

  avo: {
    titleStepTitle: 'Tribute title',
    titleStepDescription: 'The name at the top. Ex: "For my grandma" or "For my grandpa".',
    titlePlaceholder: 'Ex: For my grandma/grandpa 🌻',
    messageStepTitle: 'Your message to them',
    messageStepDescription: 'Write lovingly everything they mean to you.',
    messagePlaceholder: 'Grandma/Grandpa, you\'re one of the most special people in my life and I just had to tell you...',
    dateStepTitle: 'A special date',
    dateStepDescription: 'A birthday, a meaningful day, or any special date between you.',
    galleryStepDescription: 'The most beautiful photos of you — old ones and new ones.',
    timelineStepDescription: 'The most memorable moments you\'ve lived together.',
    musicStepDescription: 'A song that reminds you of them, or a heartfelt voice note.',
    puzzleStepDescription: 'They solve the puzzle to reveal a special photo.',
    memoryStepDescription: 'A memory match game with your photos.',
    quizStepTitle: 'How well do they know you?',
    quizStepDescription: 'Fun questions — do they know everything about you?',
    successTitle: 'Tribute ready! 🌻',
    successSubtitle: 'Send it with love and grab a tissue.',
    whatsappMessage: 'I made a special surprise for you 💝 open it when you can',
  },

  filho: {
    titleStepTitle: 'Page title',
    titleStepDescription: 'The name at the top. Ex: "For my son" or "For my daughter".',
    titlePlaceholder: 'Ex: For my son/daughter 💛',
    messageStepTitle: 'Your message to them',
    messageStepDescription: 'Write everything you feel. It will last forever.',
    messagePlaceholder: 'You have no idea how much you changed my life in ways I never imagined...',
    dateStepTitle: 'A special date',
    dateStepDescription: 'Their birthday, the day they were born, or any meaningful date.',
    galleryStepDescription: 'The most beautiful photos — from baby to today.',
    timelineStepDescription: 'The most memorable moments of their life you want to keep forever.',
    musicStepDescription: 'A song that shaped your life together, or a heartfelt voice note.',
    puzzleStepDescription: 'They solve the puzzle to reveal a special photo.',
    memoryStepDescription: 'A memory match game with your photos.',
    quizStepTitle: 'How well do they know you?',
    quizStepDescription: 'Fun questions — does your child know everything about you?',
    successTitle: 'Your surprise is ready! 💛',
    successSubtitle: 'Send it and wait for the reaction.',
    whatsappMessage: 'I made a special surprise for you 💝 open it when you can',
  },
};

export const DEFAULT_WIZARD_CONFIG_EN: WizardSegmentConfig = {
  titleStepTitle: 'Page title',
  titleStepDescription: 'Write a dedicated title. Ex: John & Mary.',
  titlePlaceholder: 'Ex: John & Mary',
  messageStepTitle: 'Your Message',
  messageStepDescription: 'Write the main message for the page.',
  messagePlaceholder: 'Write your message here...',
  dateStepTitle: 'Special Date',
  dateStepDescription: 'Enter the date that marks the beginning of it all.',
  galleryStepDescription: 'Add the photos that shaped this story.',
  timelineStepDescription: 'The most memorable moments, in chronological order.',
  musicStepDescription: 'Pick a soundtrack or record your voice.',
  puzzleStepDescription: 'A challenge before unveiling the surprise!',
  memoryStepDescription: 'Create a memory game with your photos.',
  quizStepTitle: 'Quiz',
  quizStepDescription: 'Create a fun quiz.',
  successTitle: 'Page created! 💜',
  successSubtitle: 'Share the link with someone you love.',
  whatsappMessage: 'I made a special surprise for you 💝 open it here when you can',
};
